### ISSUE TITLE
ArrayIndexOutOfBoundsException: 1 if my vector has only one dimension

### ISSUE THREAD

**Issue by invenis-paris** [irvingc/dbscan-on-spark#2]
When testing with a vector like (0, 0, 10, 10, 10, 0, 0) it fails.
You try to take the "y" component which does not exist.

`
java.lang.ArrayIndexOutOfBoundsException: 1
    at org.apache.spark.mllib.linalg.DenseVector.apply(Vectors.scala:597)
    at dbscan.DBSCANPoint.y(DBSCANPoint.scala:24)
    at dbscan.DBSCAN.dbscan$DBSCAN$$toMinimumBoundingRectangle(DBSCAN.scala:295)
    at dbscan.DBSCAN$$anonfun$3.apply(DBSCAN.scala:85)
    at dbscan.DBSCAN$$anonfun$3.apply(DBSCAN.scala:85)
...
`

BTW, does this library works with more than 2 dimensions ?

**Comment by irvingc** [comment]
Hi,

Sorry for the delay in answering. Thanks for reporting the issue! You are right, a better exception should be thrown instead of just the IndexOutOfBoundsException, since the library really expects 2 dimensions to work properly. Answering your question, only 2 dimensions are supported. Will write a fix in the upcoming days for this.

**Comment by irvingc** [comment]
closing this as a dup of #3. I am keeping #3 open because it has more discussion.
